travis:
  secure:
    BINSTAR_TOKEN: YaHVoPWlon863ECE6ZNQwne+5FFkSfrZWlCgYpm4ZHcIgYOtWJSaNIR9fQAkywaiAc6jCtC81D6viC3RWBeSxnnrX8B871FJ9CV7J06MEo5j/w5EfQw/RGr7TvugaHtwm8k9Avr9eiX9XoTVQKgLA0bI/S868t8GLeMmNfbMTdGk6Lm7f32Ti0vKv6mSyEkXbZ75a4mahyV2+Uwm9kNFLsRrGDzggnFmXzSprxI+NuUUoYnYEoClT5z1UMfO720N4GcxGNomygkcT1AHYrEpbrkyFSotwnA4NCMya/EQlsCvOet7UtQgULSjsEO09aFp06X8Vwcp7F9QAJcUUwWDfGThc8WywAEx+TlRt94azcQ33spMUJcntttFqq5IbJh4vJWLf4u8zoIpkomLiphtwIfdMd0LqTo6E1gDeC5yRk6RskLUgNCDAYtkQv6noZIAiaTetqv+84iYGAR7t7C4aYknKJhobdlejKFgqcnAdbGN5NZAIwjVw4WyNYWfRrlVstnxQNCPMpDunBp6R4zbhw6lc64o7Jd1OzkGSzEYH9oUs1bPdiubycqhuNjNDxtxQ+YlE90EgU3eSWZ6XIzbJmGvOj91/dyUY81CcTME5OTIUo7axHTpKPuYC/PU4W0k5qSmk1R3ADn0glSGwefIo0AlQej0IMcEN5QFwzAkXO8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
