travis:
  secure:
    BINSTAR_TOKEN: h3TSiZXRZnLHHTFU1MUwMFYWjfd1c3/3gWdE478BgS2rfEBMYXvUreEvlufzEh3NxAXnRw3FH0il8m8fyDv1Ss5Oxiq5iIoguFdgtbFAINmcZsa0cyz5HpA/068mNm0iwsTx95MsXxphVRIOLu3FH4BJjW4yPFcddkODtrZwE3//H6uZtLvP0cGd87GbyEZ0nNHagplYDYyYCjq9wXi3HxPZrcE2BoKny2PbUfDVW3E/BRFFCTKfoX4/Jq4lBj+MsngpFgJM5v1GkRjYeWVjQ+0Z6kET698oQXw491iw70UZO5QEJtoo1BEBLKy0cW9KvY6lhBX7m5Vw/zVrQHsc9b0xs5NQbnid7XUkidh6iaANr7/IqKoY0xzrjVUOEc4p5aI82AXs8XIGTvNkNMvhLcfd2HHNbko1eZSy+DWhMoyUoD32qQcuSvPRE0x/+Pi8YQ3pgfyaNNh6LjTqLuj6C/7eUfY4jkYZzWl0lSsS9v3wWBhyPrxmXyAa31rfUCB/AT9er8NCXo6B8x1QWteBPQkP81KtnCXRa+jgMivImXM+oVS1TZBM809teW8HeAPPAcHVFMR43L6fNV1uKo7riaf/HwmSi/iWHY4k4U2kEMzxy/URK1nmgcqIUefjbqiVdxp/PB97+bXQueuhSCBFYgWJ3+6Csw6lB979osq/59A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
