travis:
  secure:
    BINSTAR_TOKEN: rAysNumT43CD5Q1/IKWI8nJ7zn6eAbIilB+OVDmro+H2SnJvwN2xnU251q5/uivwTVpx/9yI/gzyuQnuqnmCPg1nAetrF8RpZEIzrf0mNJxq4zUYni//PO473sWN46ENr4Mt1Bl57LDcpILHP/cBeN1rEK7VLPDUF08da2qz6aOweAUBqfV8aThCT1CKD1Kw3GGev9mSVoUwBVLPmsEZg1JJ/M9oUXHgbmLx7wHnKHwRlgX+Oj7f55mi2d+PLbwWf47vwzYj6ngn2v1RWJhbtM2hAtEtC1IXOGac02/YNMyp7b8hq2s2jRG+/GErYv27siP2BgJp7MEA3G4FKC4S9bc6LuJIZEG3gp9U3KMzJFzmmZrHwveFFgsIpIZiPjuUmmvdC77kDkiu0CKbZWV2g1wqEG+7yAcaChLSocuhtHeS4YkwlLyecM2f7j9C9VqImePiIjgJDTV42LeUttIKPVOUOU2oWpYtKJXgw7gpIsXuY2uYSz1/bNG8Xj4WfhyvGsuzrSSbJjosSqimLfBfV/JCWjY3GNS7p+gczqakQd/VGOHwaAdOAQ4xnJtgCT8hisqfqj80I+WFWoj6PdjVBP+giafwRlCVsJt7UlZ7WzG0dzu1Gbc4s6PyeF0gU2ylExocWl3SoLGejcpYwB5fk/gcuO0lB0eWyP6Th0B8mVA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
